### PR TITLE
 Android v4 support from v2 branch, and bug fixes

### PR DESCRIPTION
**Pull request by andynicholson**

### CODE REVIEW

**Comment by n8fr8** [comment]
The issue I have with basing this on v2 branch is that it breaks compatibility with v1 databases, if I remember correctly... or did you not include those commits?

**Comment by andynicholson** [comment]
Right - they would be included - I blindly merged from v2 tip back to master. 
Is it a case of just needing to write SQL upgrade statements for the db ? or is there more incompatibility?

**Comment by abeluck** [comment]
Hm, perhaps we should write a migration layer to convert old databases?

**Comment by abeluck** [comment]
V2 branch is now outdated as the 4.x support and sqlcipher update were performed by n8fr8 a few months ago.  

Thanks for contributing though! We always welcome patches :)

**Pull request closed without merging**
